version: '2'

services:
    nginx:
        volumes:
            - .docker/certs:/etc/letsencrypt
        env_file:
            - ./.docker/local.env

    php:
        env_file:
            - .docker/local.env

    db:
        env_file:
            - ./.docker/local.env
        volumes:
            - .docker/db/:/docker-entrypoint-initdb.d/

#    rabbitmq:
#        env_file:
#            - ./.docker/local.env

    mail:
        container_name: selco-m2-mail
        image: schickling/mailcatcher
        ports:
            - 1025
            - 1080:1080

    blackfire:
        container_name: selco-m2-blackfire
        image: blackfire/blackfire
        env_file:
            - .docker/local.env
