set :deploy_config_path, 'cap/deploy.rb'
set :stage_config_path, 'cap/deploy'

require 'capistrano/setup'
require 'capistrano/deploy'
require 'capistrano/composer'

Dir.glob('lib/capistrano/tasks/*.cap').each { |r| import r }